---
title: "BIOL7263 - Fall 2024 - Genome Biology"
author: "Matthew Toomey"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: Cayman
    highlight: github
---

This site contains course materials for BIOL7263 Genome Biology, Fall 2024.

## Course Materials

Textbook: [Brown, T. A. (2023). Genomes 5. CRC Press.](https://www.routledge.com/Genomes-5/Brown/p/book/9780367674076)

[Course Syllabus](CourseMaterials/CourseSyllabus.html) 

[Software Installation](CourseMaterials/InstallationInstructions.html)

[Class Project Assignment](Assignments/ProjectAssignment.html) 

[Presentation sign-up sheet](https://docs.google.com/spreadsheets/d/1DVq0VemQlcY2oDZhtWaNZmfGDkfdZXTkxrJdSCjfZn8/edit?usp=sharing)

___

## Lecture Outlines & Homework Assignments

Date (week of)  | Lecture | Reading | Assignments
------------- |----------- | ------------- | ------------- 
August 29  | - [Class Introduction and OSCER](https://github.com/mbtoomey/genome_biology_FA24/blob/main/CourseMaterials/OSCER.md)<br/> - [Linux/UNIX basics](Lessons/Shell_Navigation.html)<br/> - [Git](https://github.com/mbtoomey/genome_biology_FA24/blob/main/Lessons/Lesson2.md)<br/> - [Markdown](https://github.com/mbtoomey/genome_biology_FA24/blob/main/Lessons/Lesson3.md) | - | Setup Github project with a markdown document linking to .sbatch and .sh files
September 5  | Review of DNA, RNA, and the Central Dogma | Chapter 1 (Brown) | [Begin Genomics Adventure](https://github.com/mbtoomey/genomics_adventure)  
September 12  | Sequencing Technology, Genome assembly, and alignment  | Chapter 4 (Brown) | [Genomics Adventure Chapter 2](https://github.com/mbtoomey/genomics_adventure/blob/release/chapter_2/task_1.md), [Class Project Proposal](Assignments/ProjectAssignment.html)  
September 19  | Genome annotation and QC | Chapter 5 & 6 (Brown) | [Genomics Adventure Chapter 3](https://github.com/mbtoomey/genomics_adventure/blob/release/chapter_3/task_1.md)
September 26  | Eukaryotic Genome Structure and Organization | Chapter 7 (Brown) | [Genomics Adventure Chapter 4](https://github.com/mbtoomey/genomics_adventure/blob/release/chapter_4/task_1.md)
October 3  | Prokaryotic and Viral Genome Structure and Organization, Mobile genetic elements | Chapter 8 & 9 (Brown) | [Genomics Adventure Chapter 5](https://github.com/mbtoomey/genomics_adventure/blob/release/chapter_5/task_1.md)
October 10  | Gene Expression and Transcriptomics | Chapters 10-12 (Brown) | [RNA-seq Analyses]()
October 17  | Gene Expression and Transcriptomics | Chapters 10-12 (Brown) | [RNA-seq Analyses]()
October 24  | Causes, Consequences, and Analysis of Sequence Variation | Chapters 15 & 17 (Brown) | [Variant Calling and Genome-wide FST]()
October 31  | Review and Discuss Genomics pre-print | - | [Class Project Open Session](Assignments/ProjectAssignment.html)
November 7  | Review and Discuss Genomics pre-print [Class Project Open Session](Assignments/ProjectAssignment.html) | - | [Class Project Open Session](Assignments/ProjectAssignment.html)
November 14  | [Class Project Presentations](https://docs.google.com/spreadsheets/d/1DVq0VemQlcY2oDZhtWaNZmfGDkfdZXTkxrJdSCjfZn8/edit?usp=sharing) | - | -    
November 21  | [Class Project Presentations](https://docs.google.com/spreadsheets/d/1DVq0VemQlcY2oDZhtWaNZmfGDkfdZXTkxrJdSCjfZn8/edit?usp=sharing)  | - | -  
November 28  | Thanksgiving break | - | - 
December 5  | [Class Project Presentations](https://docs.google.com/spreadsheets/d/1DVq0VemQlcY2oDZhtWaNZmfGDkfdZXTkxrJdSCjfZn8/edit?usp=sharing)  | - | - 
December 9  | Last day of classes | - | [Project Markdown Due](Assignments/ProjectAssignment.html) 

___

### Important Dates
- 30 August: Last day to add classes through self-service
- 2 September: Labor day
- 3 September: Last day to add/drop through advising
- 13 November: Last day to withdraw
- 25-29 November: Thanksgiving Break
- 9 December: Last day of classes

