---
title: "BIOL7263 - Fall 2024 - Genome Biology"
author: "Course Syllabus"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: Cayman
    highlight: github
---

___

## Class Meetings

Thursday 2:00 to 5:00 PM in Oliphant Hall Room 207

## Instructor

Matthew Toomey  
**Office**: 305 Oliphant Hall, enter OH 304 then first door on right (305)  
**Email**: [mbt6332@utulsa.edu](mailto:mbt6332@utulsa.edu)  
**Phone**: (918) 631-2206  
**Office Hours**: By appointment, in-person meetings or video conferences 

## Course description 

This seminar will introduce foundational concepts in the genome structure, function, and evolution. We will explore the sources and consequences of sequence and structural variation. We will introduce current empirical approaches in genome biology and apply these tools in exercises and a class project. Exercises will including genome assembly, alignment, annotation, and transcriptome analyses via UNIX-based bioinformatic application and [OSCER](https://www.ou.edu/oscer) computing resources. 

## Pre-Requisites
* A personal laptop computer that you bring to all lecture and lab meetings
    - Mac or Windows, with battery power to last 2.5 hours
    - all [required software packages](InstallationInstructions.html) installed and working
    - wireless access and an active TU email account
* Graduate standing as a PhD or MS student at TU
* Undergraduates by invitation only after consultation with the instructor

## Course Learning Outcomes
At the conclusion of this class students will:

1. Understand the structure and variation in genomes across the domains of life and how these are studied.     
2. Become familiar with the capabilities and limitations of current technologies genome and transcriptome sequence.
3. Gain proficiency organizing and executing bioinformatic analysis on a high performance computing cluster
4. Be ready to apply the sequence assembly, alignment, annotation, comparison, and other tools in their own research.  

## Readings

Textbook: [Brown, T. A. (2023). Genomes 5. CRC Press.](https://www.routledge.com/Genomes-5/Brown/p/book/9780367674076)

## Class policies:

I will use the [course site](https://mbtoomey.github.io/genome_biology_FA24/) to post lectures, exercises and all other course materials. Please check the site often. Students must conduct their behavior in a professional manner. To satisfy this requirement, the actions of students and their interaction with faculty members is governed by the student conduct code set forth in the [University of Tulsa Student Handbook](https://utulsa.edu/student-affairs/student-handbook-policies).

## Evaluation

**Participation** Attendance is expected at our weekly meetings. I expect you to follow along with the class presentation and exercises, running processes/code on your own computer. I expect you to work collaboratively with your colleagues and assist those in need with the exercises.   

**Exercises** There will be short assignments to give you practice using these tools introduced in the seminar. You will "turn in" assignments by posting them in markdown (.md) format to your public repository and website on GitHub.

**Project** The major goal of this course will be to complete a sequence assembly, alignment, annotation, and/or transcriptome analysis. This can be an analysis of your own data, data from your lab group, or publicly avialble sequencing data. This assignment will consist of three parts: 1) a brief research proposal, 2) a well documented and *reproducible* analysis, and 3) a class presentation reporting your results.    

### Grading 

Item |   | Total points  
:------------  | :-------------  | :------------
Participation  | -  | 100   
Exercises  | 8 x 6.25 points  | 50  
Project | -  | 150  
 **Grand total**  | -  | **300**

The grading scale will be as follows:  89.50-100% - A, 79.50-89.49% - B, 69.50-79.49% - C, 59.50-69.49% - D, < 59.50% - F. No exceptions. 

## Class Schedule

Please refer to the [course website](index.html) for an up-to-date schedule

## Academic misconduct

All instances of academic misconduct will follow the Policies and Procedures Relating to Academic Misconduct for the Oxley College of Health and Natural Sciences: 
- [All undergraduate colleges](https://univoftulsa.sharepoint.com/sites/AcademicAffairs/academicpolicies/Shared%20Documents/Forms/AllItems.aspx?id=/sites/AcademicAffairs/academicpolicies/Shared%20Documents/Unified%20Academic%20Misconduct%20Policy.pdf&parent=/sites/AcademicAffairs/academicpolicies/Shared%20Documents)
- [Graduate College](https://univoftulsa.sharepoint.com/sites/AcademicAffairs/academicpolicies/Shared%20Documents/Forms/AllItems.aspx?id=/sites/AcademicAffairs/academicpolicies/Shared%20Documents/Graduate%20School%20Academic%20Misconduct%20Policy-%20August%202017.pdf&parent=/sites/AcademicAffairs/academicpolicies/Shared%20Documents)   

Any evidence of misconduct will result in a score of zero, but students may also be dismissed from the course and automatically assigned a grade of F.

## Student Access and Success

Students who have or believe they may have a disability and would like to set up accommodations should contact Student Access within Student Success to self-identify their needs and facilitate their rights under the Americans with Disabilities Act and related laws. Student Access provides private consultations to any student.  Contact Student Access staff by email at studentaccess@utulsa.edu or by phone at 918-631-2315. The application for accommodations may be obtained online at https://sierra.accessiblelearning.com/s-UTulsa/ApplicationStudent.aspx. Student Access staff will assist students in the implementation of approved accommodations, and students should submit requests as early as possible for full assistance.  Students who qualify for accommodations should meet with the instructor privately (during office hours or by appointment) as soon as possible to arrange for their needs and obtain support for the class. Instructors are entitled to notice of 5 business days before the implementation of any required accommodations and all accommodations should be requested by the 12th week of classes for use in that semester, absent an extraordinary and unforeseeable circumstance. TU maintains a list of accessible features for all buildings (e.g., entrances, parking) at https://utulsa.edu/campus-map/.

## Artificial Intelligence 

You may use AI tools to assist with your exercises and projects.     

## Know your Title IX

Sexual misconduct is prohibited by Title IX of the Educational Amendments of 1972 ("Title IX") and will not be tolerated within the TU community.  For more information about your rights under Title IX, please visit our Policies and Laws page https://utulsa.edu/sexual-violence-prevention-education/policies-laws/ on the TU website or contact the Title IX Coordinator at 918-631-2321.  



